-- CUSTOMERS table
CREATE TABLE dbo.CUSTOMERS
(
	CID					INT IDENTITY (1,1) NOT NULL,
	ODL					NVARCHAR(7) NOT NULL,
	DOB					DATETIME,
	FullName			NVARCHAR(64) NOT NULL,
	StreetAdd			NVARCHAR(64) NOT NULL,
	CityAdd				NVARCHAR(24) NOT NULL,
	StateAdd			NVARCHAR(3) NOT NULL,
	ZipAdd				NVARCHAR(5) NOT NULL,
	CountyAdd			NVARCHAR(2) NOT NULL,
	DateSigned			DATETIME,
	CONSTRAINT[PK_dbo.CUSTOMERS] PRIMARY KEY CLUSTERED (CID ASC)
);

GO